#ATB
#Project Euler Problem #29
#Distinct powers
#How many distinct terms are in the sequence generated by a^b

distinctPowers <- function(x){
  length <- 2:x
  combinations <- combn(length, 2)
  numbers1 <- combinations[1,] ^ combinations[2,]
  numbers2 <- combinations[2,] ^ combinations[1,]
  for (i in 2:x){
    doubles[i] <- i^i
  }
  allpowers <- c(doubles, numbers1, numbers2)
  return(length(unique(allpowers)))
}